// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function BeginNativeFileDrag(arg1:string):Promise<void>;

export function BuildBatchOutputPath(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Cancel(arg1:string):Promise<void>;

export function ChooseBatchInputDir():Promise<backend.BatchInputDirectory>;

export function ChooseBatchOutputDir():Promise<string>;

export function ChooseOutputDir():Promise<string>;

export function ClearLocalCredentialFiles():Promise<void>;

export function ClearPSBridgeProfile():Promise<void>;

export function CompletePSBridgeRemoteJob(arg1:backend.PSBridgeRemoteCompletion):Promise<void>;

export function CropImage(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<backend.ImageTransformResult>;

export function DeleteStoredAPIKey(arg1:string):Promise<void>;

export function Edit(arg1:backend.GenerateOptions):Promise<backend.JobStarted>;

export function ExportHistoryToFile(arg1:string):Promise<string>;

export function FailPSBridgeRemoteJob(arg1:backend.PSBridgeRemoteFailure):Promise<void>;

export function FlipImage(arg1:string,arg2:boolean):Promise<backend.ImageTransformResult>;

export function Generate(arg1:backend.GenerateOptions):Promise<backend.JobStarted>;

export function GetAutomationStatus():Promise<backend.AutomationStatus>;

export function GetOutputDir():Promise<string>;

export function GetStoredAPIKey(arg1:string):Promise<string>;

export function ImportHistoryFromFile():Promise<string>;

export function ImportImageFromB64(arg1:string,arg2:string):Promise<backend.ImportedImage>;

export function ImportImagePath(arg1:string):Promise<backend.ImportedImage>;

export function ListBatchInputImages(arg1:string):Promise<backend.BatchInputDirectory>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenImageDialog():Promise<backend.SelectFileResponse>;

export function OpenImagesDialog():Promise<backend.SelectFilesResponse>;

export function OpenMaterialSyncDir(arg1:string):Promise<void>;

export function OpenOutputDir():Promise<void>;

export function OptimizePrompt(arg1:backend.PromptOptimizeOptions):Promise<string>;

export function ProbeUpstream(arg1:backend.ProbeUpstreamOptions):Promise<backend.ProbeUpstreamResult>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RegisterImportedImageAsset(arg1:string):Promise<backend.MediaAssetRef>;

export function RegisterMediaAsset(arg1:string,arg2:string):Promise<backend.MediaAssetRef>;

export function ReversePrompt(arg1:backend.PromptReverseOptions):Promise<string>;

export function RotateImage(arg1:string,arg2:number):Promise<backend.ImageTransformResult>;

export function SaveImageAs(arg1:string,arg2:string):Promise<string>;

export function SaveImagePathAs(arg1:string,arg2:string):Promise<string>;

export function SaveImagePathToDir(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveImageToDir(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetOutputDir(arg1:string):Promise<void>;

export function SetStoredAPIKey(arg1:string,arg2:string):Promise<void>;

export function SyncCLIConfig(arg1:backend.CLIConfigSyncInput):Promise<backend.CLIConfigSyncResult>;

export function SyncMaterialGroupToOutput(arg1:string,arg2:string,arg3:Array<backend.MaterialOutputSyncItem>):Promise<backend.MaterialOutputSyncResult>;

export function SyncPSBridgeProfile(arg1:backend.PSBridgeProfileInput):Promise<backend.PSBridgeStatus>;

export function UpdatePSBridgeRemoteJob(arg1:backend.PSBridgeRemoteProgress):Promise<void>;
