// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginNativeFileDrag(arg1) {
  return window['go']['backend']['DesktopAPI']['BeginNativeFileDrag'](arg1);
}

export function BuildBatchOutputPath(arg1, arg2, arg3) {
  return window['go']['backend']['DesktopAPI']['BuildBatchOutputPath'](arg1, arg2, arg3);
}

export function Cancel(arg1) {
  return window['go']['backend']['DesktopAPI']['Cancel'](arg1);
}

export function ChooseBatchInputDir() {
  return window['go']['backend']['DesktopAPI']['ChooseBatchInputDir']();
}

export function ChooseBatchOutputDir() {
  return window['go']['backend']['DesktopAPI']['ChooseBatchOutputDir']();
}

export function ChooseOutputDir() {
  return window['go']['backend']['DesktopAPI']['ChooseOutputDir']();
}

export function ClearLocalCredentialFiles() {
  return window['go']['backend']['DesktopAPI']['ClearLocalCredentialFiles']();
}

export function ClearPSBridgeProfile() {
  return window['go']['backend']['DesktopAPI']['ClearPSBridgeProfile']();
}

export function CompletePSBridgeRemoteJob(arg1) {
  return window['go']['backend']['DesktopAPI']['CompletePSBridgeRemoteJob'](arg1);
}

export function CropImage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['DesktopAPI']['CropImage'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteStoredAPIKey(arg1) {
  return window['go']['backend']['DesktopAPI']['DeleteStoredAPIKey'](arg1);
}

export function Edit(arg1) {
  return window['go']['backend']['DesktopAPI']['Edit'](arg1);
}

export function ExportHistoryToFile(arg1) {
  return window['go']['backend']['DesktopAPI']['ExportHistoryToFile'](arg1);
}

export function FailPSBridgeRemoteJob(arg1) {
  return window['go']['backend']['DesktopAPI']['FailPSBridgeRemoteJob'](arg1);
}

export function FlipImage(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['FlipImage'](arg1, arg2);
}

export function Generate(arg1) {
  return window['go']['backend']['DesktopAPI']['Generate'](arg1);
}

export function GetAutomationStatus() {
  return window['go']['backend']['DesktopAPI']['GetAutomationStatus']();
}

export function GetOutputDir() {
  return window['go']['backend']['DesktopAPI']['GetOutputDir']();
}

export function GetStoredAPIKey(arg1) {
  return window['go']['backend']['DesktopAPI']['GetStoredAPIKey'](arg1);
}

export function ImportHistoryFromFile() {
  return window['go']['backend']['DesktopAPI']['ImportHistoryFromFile']();
}

export function ImportImageFromB64(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['ImportImageFromB64'](arg1, arg2);
}

export function ImportImagePath(arg1) {
  return window['go']['backend']['DesktopAPI']['ImportImagePath'](arg1);
}

export function ListBatchInputImages(arg1) {
  return window['go']['backend']['DesktopAPI']['ListBatchInputImages'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['backend']['DesktopAPI']['OpenExternalURL'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['backend']['DesktopAPI']['OpenFile'](arg1);
}

export function OpenImageDialog() {
  return window['go']['backend']['DesktopAPI']['OpenImageDialog']();
}

export function OpenImagesDialog() {
  return window['go']['backend']['DesktopAPI']['OpenImagesDialog']();
}

export function OpenMaterialSyncDir(arg1) {
  return window['go']['backend']['DesktopAPI']['OpenMaterialSyncDir'](arg1);
}

export function OpenOutputDir() {
  return window['go']['backend']['DesktopAPI']['OpenOutputDir']();
}

export function OptimizePrompt(arg1) {
  return window['go']['backend']['DesktopAPI']['OptimizePrompt'](arg1);
}

export function ProbeUpstream(arg1) {
  return window['go']['backend']['DesktopAPI']['ProbeUpstream'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['backend']['DesktopAPI']['ReadImageAsBase64'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['backend']['DesktopAPI']['ReadTextFile'](arg1);
}

export function RegisterImportedImageAsset(arg1) {
  return window['go']['backend']['DesktopAPI']['RegisterImportedImageAsset'](arg1);
}

export function RegisterMediaAsset(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['RegisterMediaAsset'](arg1, arg2);
}

export function ReversePrompt(arg1) {
  return window['go']['backend']['DesktopAPI']['ReversePrompt'](arg1);
}

export function RotateImage(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['RotateImage'](arg1, arg2);
}

export function SaveImageAs(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['SaveImageAs'](arg1, arg2);
}

export function SaveImagePathAs(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['SaveImagePathAs'](arg1, arg2);
}

export function SaveImagePathToDir(arg1, arg2, arg3) {
  return window['go']['backend']['DesktopAPI']['SaveImagePathToDir'](arg1, arg2, arg3);
}

export function SaveImageToDir(arg1, arg2, arg3) {
  return window['go']['backend']['DesktopAPI']['SaveImageToDir'](arg1, arg2, arg3);
}

export function SetOutputDir(arg1) {
  return window['go']['backend']['DesktopAPI']['SetOutputDir'](arg1);
}

export function SetStoredAPIKey(arg1, arg2) {
  return window['go']['backend']['DesktopAPI']['SetStoredAPIKey'](arg1, arg2);
}

export function SyncCLIConfig(arg1) {
  return window['go']['backend']['DesktopAPI']['SyncCLIConfig'](arg1);
}

export function SyncMaterialGroupToOutput(arg1, arg2, arg3) {
  return window['go']['backend']['DesktopAPI']['SyncMaterialGroupToOutput'](arg1, arg2, arg3);
}

export function SyncPSBridgeProfile(arg1) {
  return window['go']['backend']['DesktopAPI']['SyncPSBridgeProfile'](arg1);
}

export function UpdatePSBridgeRemoteJob(arg1) {
  return window['go']['backend']['DesktopAPI']['UpdatePSBridgeRemoteJob'](arg1);
}
