// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function ChooseOutputDir():Promise<string>;

export function CropImage(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<backend.ImageTransformResult>;

export function DeleteStoredAPIKey(arg1:string):Promise<void>;

export function Edit(arg1:backend.GenerateOptions):Promise<backend.JobStarted>;

export function ExportHistoryToFile(arg1:string):Promise<string>;

export function FlipImage(arg1:string,arg2:boolean):Promise<backend.ImageTransformResult>;

export function Generate(arg1:backend.GenerateOptions):Promise<backend.JobStarted>;

export function GetOutputDir():Promise<string>;

export function GetStoredAPIKey(arg1:string):Promise<string>;

export function ImportHistoryFromFile():Promise<string>;

export function ImportImageFromB64(arg1:string,arg2:string):Promise<backend.ImportedImage>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenImageDialog():Promise<backend.SelectFileResponse>;

export function OpenOutputDir():Promise<void>;

export function OptimizePrompt(arg1:backend.PromptOptimizeOptions):Promise<string>;

export function ProbeUpstream(arg1:backend.ProbeUpstreamOptions):Promise<backend.ProbeUpstreamResult>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RegisterMediaAsset(arg1:string,arg2:string):Promise<backend.MediaAssetRef>;

export function RegisterImportedImageAsset(arg1:string):Promise<backend.MediaAssetRef>;

export function RegisterTrustedOutputDir(arg1:string):Promise<void>;

export function RotateImage(arg1:string,arg2:number):Promise<backend.ImageTransformResult>;

export function SaveImageAs(arg1:string,arg2:string):Promise<string>;

export function SaveImagePathAs(arg1:string,arg2:string):Promise<string>;

export function SaveImageToDir(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveImagePathToDir(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetOutputDir(arg1:string):Promise<void>;

export function SetStoredAPIKey(arg1:string,arg2:string):Promise<void>;
