// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['backend']['Service']['Cancel'](arg1);
}

export function ChooseOutputDir() {
  return window['go']['backend']['Service']['ChooseOutputDir']();
}

export function CropImage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['Service']['CropImage'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteStoredAPIKey(arg1) {
  return window['go']['backend']['Service']['DeleteStoredAPIKey'](arg1);
}

export function Edit(arg1) {
  return window['go']['backend']['Service']['Edit'](arg1);
}

export function ExportHistoryToFile(arg1) {
  return window['go']['backend']['Service']['ExportHistoryToFile'](arg1);
}

export function FlipImage(arg1, arg2) {
  return window['go']['backend']['Service']['FlipImage'](arg1, arg2);
}

export function Generate(arg1) {
  return window['go']['backend']['Service']['Generate'](arg1);
}

export function GetOutputDir() {
  return window['go']['backend']['Service']['GetOutputDir']();
}

export function GetStoredAPIKey(arg1) {
  return window['go']['backend']['Service']['GetStoredAPIKey'](arg1);
}

export function ImportHistoryFromFile() {
  return window['go']['backend']['Service']['ImportHistoryFromFile']();
}

export function ImportImageFromB64(arg1, arg2) {
  return window['go']['backend']['Service']['ImportImageFromB64'](arg1, arg2);
}

export function OpenExternalURL(arg1) {
  return window['go']['backend']['Service']['OpenExternalURL'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['backend']['Service']['OpenFile'](arg1);
}

export function OpenImageDialog() {
  return window['go']['backend']['Service']['OpenImageDialog']();
}

export function OpenOutputDir() {
  return window['go']['backend']['Service']['OpenOutputDir']();
}

export function OptimizePrompt(arg1) {
  return window['go']['backend']['Service']['OptimizePrompt'](arg1);
}

export function ProbeUpstream(arg1) {
  return window['go']['backend']['Service']['ProbeUpstream'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['backend']['Service']['ReadImageAsBase64'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['backend']['Service']['ReadTextFile'](arg1);
}

export function RegisterMediaAsset(arg1, arg2) {
  return window['go']['backend']['Service']['RegisterMediaAsset'](arg1, arg2);
}

export function RegisterImportedImageAsset(arg1) {
  return window['go']['backend']['Service']['RegisterImportedImageAsset'](arg1);
}

export function RegisterTrustedOutputDir(arg1) {
  return window['go']['backend']['Service']['RegisterTrustedOutputDir'](arg1);
}

export function RotateImage(arg1, arg2) {
  return window['go']['backend']['Service']['RotateImage'](arg1, arg2);
}

export function SaveImageAs(arg1, arg2) {
  return window['go']['backend']['Service']['SaveImageAs'](arg1, arg2);
}

export function SaveImagePathAs(arg1, arg2) {
  return window['go']['backend']['Service']['SaveImagePathAs'](arg1, arg2);
}

export function SaveImageToDir(arg1, arg2, arg3) {
  return window['go']['backend']['Service']['SaveImageToDir'](arg1, arg2, arg3);
}

export function SaveImagePathToDir(arg1, arg2, arg3) {
  return window['go']['backend']['Service']['SaveImagePathToDir'](arg1, arg2, arg3);
}

export function SetOutputDir(arg1) {
  return window['go']['backend']['Service']['SetOutputDir'](arg1);
}

export function SetStoredAPIKey(arg1, arg2) {
  return window['go']['backend']['Service']['SetStoredAPIKey'](arg1, arg2);
}
