import { useStudioStore } from "../../state/studioStore";
import { applyTheme } from "../../state/studioStore.shared";
import { buildMacWorkspacePreview, readPreviewScenario } from "./previewData";

export { readPreviewScenario } from "./previewData";

export function applyMacWorkspacePreviewToStore(workspaceId = "preview-workspace") {
  const preview = buildMacWorkspacePreview(workspaceId);
  applyTheme("dark");
  document.documentElement.style.setProperty("--font-scale", "1");

  useStudioStore.setState({
    apiKey: "sk-preview",
    mode: "edit",
    promptPrefix: preview.workspace.promptPrefix,
    prompt: preview.currentImage.prompt,
    negativePrompt: preview.currentImage.negativePrompt ?? "",
    size: preview.currentImage.size,
    quality: preview.currentImage.quality,
    outputFormat: "png",
    seed: preview.currentImage.seed ?? 3200,
    kernelRuntimeMode: "auto",
    baseURL: preview.profile.baseURL,
    textModelID: preview.profile.textModelID,
    imageModelID: preview.profile.imageModelID,
    apiMode: preview.profile.apiMode,
    requestPolicy: preview.profile.requestPolicy,
    noPromptRevision: true,
    profiles: [preview.profile],
    activeProfileId: preview.profile.id,
    sources: preview.sources,
    runningJobs: [],
    jobsTotal: 0,
    jobsCompleted: 0,
    progress: null,
    streamPreview: null,
    streamPreviews: {},
    lastLogLine: "",
    errorMessage: null,
    errorRawPath: null,
    isRunning: false,
    lastPayload: null,
    runningJobMeta: {},
    currentImage: preview.currentImage,
    history: preview.history,
    batchResults: [],
    resultGridOpen: false,
    historyRailCollapsed: false,
    historyTimelineOpen: false,
    tool: "pan",
    brushSize: 24,
    brushMode: "paint",
    annotationKind: "rect",
    annotationColor: "#ff4d4d",
    selectedAnnotationId: null,
    maskDataURL: null,
    strokes: [],
    annotations: [],
    compareB: null,
    compareSplit: 0.5,
    toasts: [],
    recentDurations: preview.history.map((item) => item.elapsedSec ?? 0).filter((value) => value > 0),
    viewZoom: 1,
    canvasViewResetTick: 0,
    fullscreen: false,
    promptHistory: [],
    batchCount: 1,
    presets: [],
    theme: "dark",
    fontScale: 1,
    workspaces: [preview.workspace],
    activeWorkspaceId: workspaceId,
    styleTag: preview.currentImage.styleTag ?? "",
    undoStack: [],
    redoStack: [],
    resultDetail: null,
    settingsOpen: false,
    isTestingKey: false,
    isOptimizingPrompt: false,
    upstreamModalOpen: false,
    upstreamReturnTarget: "app",
    starPromptOpen: false,
    starPromptSource: "auto",
  });
}
